#[path = "app/api.rs"]
pub mod api;
#[path = "app/appdb.rs"]
pub mod appdb;
#[path = "app/auth.rs"]
pub mod auth;
#[path = "app/config.rs"]
pub mod config;
#[path = "app/embed.rs"]
pub mod embed;
#[path = "app/endpoint.rs"]
pub(crate) mod endpoint;
#[path = "app/harness.rs"]
pub mod harness;
#[path = "app/knowledge.rs"]
pub mod knowledge;
#[path = "app/llm.rs"]
pub mod llm;
#[path = "app/places.rs"]
pub mod places;
#[path = "app/prompt.rs"]
pub mod prompt;
#[path = "app/rank.rs"]
pub mod rank;
#[path = "app/speech.rs"]
pub mod speech;
#[path = "app/sse.rs"]
pub mod sse;
#[path = "app/tools.rs"]
pub mod tools;
