# Database files. Kept across pod restarts.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: styrta
  labels:
    app.kubernetes.io/name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 10Gi
